= Spock with String Kotlin-Powered Types Sandbox

*Features*

* Kotlin Production code with Strong Types
* Kotlin Testfixture Builders
* link:http://spockframework.org/[Spock]
* link:https://junit.org/junit5/[JUnit5] for comparison with Spock

== Usage

* Build complete project `./gradlew build`
** Two tests will fail because a contract is not fulfilled by an implementation. See <<contract-tests, Contract Tests>> for more information.

== Strong types

By strong types I mean that name and age are not `String` and `Int` but represented by the types link:main/src/main/kotlin/de/richargh/sandbox/spock/strongtypes/Name.kt[Name] and link:main/src/main/kotlin/de/richargh/sandbox/spock/strongtypes/Age.kt[Age].

I want to use strong types

. to be more precise in my code (the thing you are using is not a number, but an age)
. to be able to constrain these types if needed (a name must not be empty, an age must not be negative)
. and to create more robust code where passing the wrong type is forbidden by the compiler.

At the same time I want to write compact, focused, noise- and fluff-less tests that used the primitive values instead of the strong types.

This sandbox compares the simple ways that Spock and Junit5 allow implicit and explicit type conversions for parameterized/data-driven tests.

== Test impressions

The tests here are not my best work (I'd say that `all names are allowed` is laughably bad because the test is in the data generator).
They do serve their purpose though and help me illustrate and compare Spock (and Junit5) features when trying to use strong types in Kotlin.

Junit5 has the `@CsvSource` Annotation for tabular data-driven tests, Spock has the table syntax feature.

=== JUnit5

Junit5 provides a link:https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion-implicit-fallback[implicit and explicit] String to Object conversions.
A String can be converted to the target type if:

* the target type has a `static method` (name does not matter) that takes a `String` and returns an instance of the target or a `secondary constructor` that takes a `String`. That's why we have an `Age.of` method that is annotated with `@JvmStatic`.
* the test method parameter is annotated with a `@ConvertWith(MyConverter::class)` that implements `SimpleArgumentConverter` or `TypedArgumentConverter`. You can even write your own Meta-Annotation like `@ConvertNameToPerson` or the `JavaTimeConversionPattern` included with JUnit5.
* the test method parameter is annotated with `@AggregateWith((MyAggregator::class)` that implements `ArgumentsAggregator`. This class can now decide how to aggregate the CsvSource arguments into a single object. You can also write a meta-annotation for this.

=== Spock

Spock does not provide such annotations, implicit or explicity, at least I could not find any.

NOTE: Groovy (the underlying language of Spock) does provide a feature called link:https://groovy-lang.org/operators.html#_coercion_operator[Type Coercion] however.
Groovy also provides link:https://groovy-lang.org/metaprogramming.html#_extension_modules[Extension Modules] that we can add via Module Descriptor by creating a resources file called `org.codehaus.groovy.runtime.ExtensionModule`.

In Groovy we can write link:main/src/test/groovy/de/richargh/sandbox/spock/strongtypes/StringConversions.groovy[StringConversions] that provide a conversion from String to Person (or Name) which gives us the possibility to write `Person person = "John" as Person"`.

Sadly Spock does not use type coercion yet.

NOTE: A pull request that adds type coercion was merged to spock master on link:https://github.com/spockframework/spock/pull/1280[Feburary 23rd 2021]. Depending on your Spock version type coercion might already be supported. Huge thanks to the Spock time for adding this so quickly.

Most versions of Spock won't convert from String to Name and Int to Age in the following table:

[source]
----
where:
name   | age
"John" | 5
"Lisa" | 25
----

To solve this we could write:
[source]
----
where:
name            | age
Name.of("John") | new Age(5)
Name.of("Lisa") | new Age(25)
----

but since that adds too much noise to the table we'd probably write:
[source]
----
where:
theName | theAge
"John"  | 5
"Lisa"  | 2

name = Name.of(theName)
age = new Age(theAge)
// or use type coercion directly:
// name = theName as Name
----

We could also create an Extension like the link:main/src/test/groovy/de/richargh/sandbox/spock/strongtypes/MakePersonExtension.groovy[MakePersonExtension] that does the type conversion for us.

[[contract-tests]]
== Contract Tests

In addition to the strong types test, this project also implements link:https://blog.thecodewhisperer.com/permalink/getting-started-with-contract-tests[Contract Tests] (for another example see link:http://richargh.de/posts/Contract-Tests-in-Kotlin[here]).
One abstract link:main/src/test/groovy/de/richargh/sandbox/spock/strongtypes/PeopleContractSpec.groovy[PeopleContractSpec (Spock)] or link:main/src/test/kotlin/de/richargh/sandbox/spock/strongtypes/PeopleContract.kt[PeopleContract (Junit5)] and one or more concrete classes that inject the dependencies to see if they fulfill the contract.
The link:main/src/testFixtures/kotlin/de/richargh/sandbox/spock/strongtypes/NoopPeople.kt[NoopPeople] implementation doesn't fulfill the contract for link:main/src/main/kotlin/de/richargh/sandbox/spock/strongtypes/People.kt[People], which is why the tests are red.